### ISSUE TITLE
get_one helper?

### ISSUE THREAD

**Issue by hadley** [metacran/desc#27]
Something like:

```R
get_one <- function(key) {
  fields <- self$get(key)
  if (length(fields)  != 1) {
   stop(length(fields), " fields, not one", call. = FALSE)
  }
  
  fields[[1]]
}
```

Maybe `get_value()`? Or `get_single()`?

**Comment by gaborcsardi** [comment]
How about `get_one_of()`? (I assume this is for the `length(key) > 1` cases?)

Btw. what would you use it for?

**Comment by hadley** [comment]
I find myself doing `desc$get("Title")[[1]]` a lot, and it makes me nervous that it will fail silently if I misspell title in the code or the DESCRIPTION.  

I'd rather have it throw an error if there isn't exactly one element. A `get_first()` might also be useful though.

**Comment by gaborcsardi** [comment]
Oh, I see. It will always be exactly one element, actually. But if title is misspelled here or there, then it will return `NA`. So I guess you want a version that fails instead of returning `NA`s. That makes sense.

OK, so the only question is the name now, that expresses that it works *surly*. I don't have a really good choise, `get_value` is not bad, but not optimal I think.

How about `desc$have()`? `desc$get_surly()` is also not too bad, although a tiny bit long.

**Comment by hadley** [comment]
I'd expect `have()` to return a logical. What about `get_exact()`?

**Comment by gaborcsardi** [comment]
`get_or_fail()`? Otherwise `get_exact()` it is....

**Comment by hadley** [comment]
I like `get_or_fail()`

**Comment by gaborcsardi** [comment]
:+1:
